deployment:
  staging:
    branch: master
    commands:
          - aws s3 sync ./../ s3://jjnewsbackup/ --delete
    codedeploy:
      JJNews:
        application_root: /
        region: us-west-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: jjnewsbackup
            key_pattern: JJNews-{BRANCH}-{SHORT_COMMIT}
        deployment_group: JJNewsGroup